[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "clinical-variant-ark>=4.1.3",
    "cryptography>=44.0.2",
    "grpcio-tools>=1.70.0",
    "grpcio>=1.70.0",
    "psutil>=7.0.0",
    "twilio>=9.4.6",
]
